# Generated by Django 3.0.5 on 2020-05-01 17:21

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('MockSchedularApp', 'MockSchedular')
    Student(name="Joe Silver", email="joe@email.com", day="2020-10-10", time="08:08:08", about="DSA").save()

class Migration(migrations.Migration):

    dependencies = [
        ('MockSchedularApp', '0001_initial'),
    ]

    operations = [
    ]
