# Generated by Django 3.0.5 on 2020-05-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MockSchedularApp', '0002_MockSchedularApp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='MockSchedular',
        ),
    ]
