# Generated by Django 3.0.5 on 2020-05-04 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockSchedularApp', '0003_auto_20200501_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockschedular',
            name='date',
        ),
        migrations.AddField(
            model_name='mockschedular',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
