# Generated by Django 3.0.5 on 2020-05-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentBody', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('subject', models.CharField(max_length=101)),
                ('year', models.IntegerField(default=0)),
                ('resourceType', models.CharField(default='Video', max_length=20)),
                ('semester', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
