# Generated by Django 3.0.5 on 2020-08-25 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(default='user', max_length=15)),
                ('rollNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('subject', models.CharField(max_length=101)),
                ('year', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('uploadedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('commentBody', models.CharField(default='', max_length=1000)),
                ('videocontent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='VideoModule.VideoContent')),
            ],
        ),
    ]
