# Generated by Django 3.0.5 on 2020-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=15)),
                ('rollNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default='author', max_length=20),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentBody',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
