# Generated by Django 3.0.5 on 2020-05-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoModule', '0002_auto_20200502_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videoModule.Comments'),
        ),
    ]
