# Generated by Django 3.0.5 on 2020-05-02 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoModule', '0003_videocontent_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.OneToOneField(default='author', on_delete=django.db.models.deletion.CASCADE, to='videoModule.User'),
        ),
    ]
