# Generated by Django 3.0.5 on 2020-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoModule', '0004_auto_20200502_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='authorName',
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
