# Generated by Django 3.0.5 on 2020-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoModule', '0005_auto_20200502_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
