# Generated by Django 3.0.5 on 2020-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoModule', '0006_auto_20200502_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
