# Generated by Django 3.0.5 on 2020-05-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoModule', '0008_auto_20200502_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='uploadedBy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='videocontent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='videoModule.VideoContent'),
        ),
    ]
