# Generated by Django 3.0.5 on 2020-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoModule', '0009_auto_20200503_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='speaker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
