# Generated by Django 3.0.5 on 2020-08-25 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('author', models.CharField(default='Admin', max_length=141)),
                ('subject', models.CharField(max_length=101)),
                ('year', models.IntegerField()),
                ('resourceType', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.IntegerField()),
                ('numberofUpvotes', models.IntegerField(default=0)),
                ('numberofDownvotes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=141)),
                ('title', models.CharField(max_length=101)),
                ('yearPlaced', models.IntegerField()),
                ('experience', models.CharField(blank=True, max_length=2000, null=True)),
                ('yearPassout', models.IntegerField()),
                ('company', models.CharField(default='', max_length=20)),
                ('numberofUpvotes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('EmailId', models.EmailField(max_length=100)),
                ('role', models.CharField(default='student', max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('rollNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsPYQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('commentBody', models.CharField(default='', max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('pyq', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SCPapp.File')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('commentBody', models.CharField(default='', max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('exp', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SCPapp.Interview')),
            ],
        ),
    ]
