# Generated by Django 3.0.5 on 2020-09-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailVerify',
            fields=[
                ('rollNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EmailId', models.EmailField(max_length=100)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
