# Generated by Django 3.0.5 on 2020-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='subject',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
