# Generated by Django 3.0.5 on 2020-04-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0002_file_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.CharField(max_length=101),
        ),
    ]
