# Generated by Django 3.0.5 on 2020-09-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0002_emailverify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverify',
            old_name='EmailId',
            new_name='email',
        ),
    ]
