# Generated by Django 3.0.5 on 2020-04-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0003_auto_20200428_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resourceType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
