# Generated by Django 3.0.5 on 2020-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0004_auto_20200428_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='numberofDownvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='numberofUpvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
