# Generated by Django 3.0.2 on 2020-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0004_auto_20200428_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='numberofDownvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='numberofUpvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.IntegerField(),
        ),
    ]
