# Generated by Django 3.0.5 on 2020-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0005_auto_20200501_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='numberofDownvotes',
        ),
        migrations.RemoveField(
            model_name='file',
            name='numberofUpvotes',
        ),
        migrations.AlterField(
            model_name='file',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.IntegerField(),
        ),
    ]
