# Generated by Django 3.0.2 on 2020-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0005_auto_20200430_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('title', models.CharField(max_length=101)),
                ('yearPlaced', models.IntegerField()),
                ('experience', models.CharField(blank=True, max_length=2000, null=True)),
                ('yearPassout', models.IntegerField()),
                ('numberofUpvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
