# Generated by Django 3.0.2 on 2020-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0006_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('EmailId', models.EmailField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('rollNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
