# Generated by Django 3.0.2 on 2020-05-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0008_auto_20200511_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
    ]
