# Generated by Django 3.0.2 on 2020-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0009_remove_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
