# Generated by Django 3.0.2 on 2020-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0010_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='rollNumber',
            field=models.CharField(max_length=10),
        ),
    ]
